### ISSUE TITLE
Please add extension settings in order to add default "Color Based On" value

### ISSUE THREAD

**Issue by PawelStadnicki** [RandomFractals/unfolded-map-renderer#4]
Is it possible to add vscode extension settings?

In particular there could be map style/theme selection (exactly like Geo Data Viewer has it)
plus I would really appreciate a possiblity to have default FillColor -> Color Based On
option selectable on extension setting rather than for each execution.

Moreover, is it possible to FillColor from a particular property that stores color ?
In that case Color Scale is not needed.

For example I have geojson created for www.geojson.io, which expect the color to be in "fill" property,
it would be awesome to have the possibility.

![image](https://user-images.githubusercontent.com/56049414/161970334-cde8dfd7-5860-4057-9302-a6bbf9418ec2.png)

If my suggestions are possible  I will be a very happy to become monthly ko-fi supporter.

**Comment by RandomFractals** [comment]
@PawelStadnicki this unfolded map renderer extension was a one off for me to show what's possible with maps in vscode notebooks. It's very low in terms of installs or dev interest in vscode extensions marketplace for me to consider this feature enhancement. 

I don't plant to maintain it, but I'll accept PRs & republish if @heshan0131 or @ibgreen & team would like to contribute it.
